// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rixdalictpsibaczvmbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpeGRhbGljdHBzaWJhY3p2bWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDMxNDUsImV4cCI6MjA2MDk3OTE0NX0.IYjq6UJqEYNItvteyfDn3Tuke3p8G-2py-lAliQxFoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);